name: Build on branch
on:
  push:
    branches-ignore:
      - 'main'

jobs:
  publish:
    name: Package
    runs-on:
      - ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.OCI_REGISTRY_USER }}
          password: ${{ secrets.OCI_REGISTRY_PASS }}
      - id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - id: test
        run: mvn verify
      - id: setup-pack
        uses: buildpacks/github-actions/setup-pack@v4.9.1
      - id: package
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          VERSION=$(git rev-parse --short=8 HEAD)
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY}"
          pack build ${IMAGE_NAME}:${VERSION} \
            --builder paketobuildpacks/builder:tiny \
            --publish \
            --env BP_JVM_VERSION=17 \
            --env BP_OCI_SOURCE=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY
          DIGEST="$(crane digest ${IMAGE_NAME}:${VERSION})"
          echo "::set-output name=id::${IMAGE_NAME}"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=digest::${IMAGE_NAME}@${DIGEST}"
        shell: bash
