name: Deployment

on:
  workflow_call:
    inputs:
      version:
        description: 'A version to be deployed'
        required: true
        type: string
      environment:
        description: 'A target to deploy to'
        default: test
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'A version to be deployed'
        type: string
        required: true
      environment:
        description: 'A target to deploy to'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - test
jobs:
  deploy-to-helm:
    runs-on: ubuntu-latest
    environment:
      name: springboot-helm-${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: update image tag
        uses: mikefarah/yq@v4.28.2
        with:
          cmd: |
            yq -i \
              '."spring-boot-helm-demo".image.tag="${{ inputs.version }}"' \
              helm/springboot-helm-${{ inputs.environment }}/values.yaml
      - uses: EndBug/add-and-commit@v9.1.1
        with:
          add: helm/springboot-helm-${{ inputs.environment }}/values.yaml
          message: "deploy version ${{ inputs.version }} to springboot-helm-${{ inputs.environment }}"
          pull: '--rebase'
  deploy-to-multisource-files:
    runs-on: ubuntu-latest
    environment:
      name: springboot-multisource-files-${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: update image tag
        run: |
          sed -i \
            's/tag:\ [[:digit:]].[[:digit:]].[[:digit:]]/tag: ${{ inputs.version }}/' \
            .argo-multisource-files/${{ inputs.environment }}.yaml
      - uses: EndBug/add-and-commit@v9.1.1
        with:
          add: .argo-multisource-files/${{ inputs.environment }}.yaml
          message: "deploy version ${{ inputs.version }} to springboot-multisource-files-${{ inputs.environment }}"
          pull: '--rebase'
    needs: deploy-to-helm # does not need the job, but delays until commit is done