name: Deployment

on:
  workflow_call:
    inputs:
      version:
        description: 'A version to be deployed'
        required: true
        type: string
      environment:
        description: 'A target to deploy to'
        default: test
        type: string

jobs:
  deploy-to-helm:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.target }}
    steps:
      - uses: actions/checkout@v2
      - name: update image tag
        uses: mikefarah/yq@v4.28.2
        with:
          cmd: |
            yq -i \
              '."spring-boot-helm-demo".image.tag="${{ inputs.version }}"' \
              helm/springboot-helm-${{ inputs.environment }}/values.yaml
      - uses: EndBug/add-and-commit@v9.1.1
        with:
          add: helm/springboot-helm-${{ inputs.environment }}/values.yaml
          message: "deploy version ${{ inputs.version }} to ${{ inputs.environment }}"
