# bump version
name: Bump version
on:
  push:
    paths-ignore:
      - 'deployment/**'
jobs:
  bump:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: '0'
      - id: github-tag
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
    outputs:
      version: ${{ steps.github-tag.outputs.new_tag }}
  call-release-workflow:
    uses: dhenne/spring-boot-service/.github/workflows/release.yml@main
    needs: bump
    with:
      version: ${{ needs.bump.outputs.version }}
    secrets:
      OCI_REGISTRY_USER: ${{ secrets.OCI_REGISTRY_USER }}
      OCI_REGISTRY_PASS: ${{ secrets.OCI_REGISTRY_PASS }}
